### ISSUE TITLE
#1 - Create Menu

### ISSUE THREAD

**Issue by WikiWikiWasp** [WikiWikiWasp/Unix-Project-1#1]
Create a menu for users to interact with the database.

Basic menu provided in Assignment:
```
Welcome to my contact database, please select in the following menu:
(a) Find a record
(b) Update a record
(c) Update a record
(d) Remove a record
(e) Quit
> Selection is : 
```

- [ ] User input validation

**Comment by Car234** [comment]
http://askubuntu.com/questions/1705/how-can-i-create-a-select-menu-in-a-shell-script

**Comment by mcdermottsolutions** [comment]
Closing - I believe this is finished.  If you see any issues, let me know.
